apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: info-app
  template:
    metadata:
      labels:
        app: info-app
    spec:
      containers:
      - name: my-python-app
        image: info-app:v1  # <--- Match the name you used in the 'docker build'
        imagePullPolicy: IfNotPresent  # <--- THIS IS THE FIX
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: info-app-service
spec:
  type: LoadBalancer
  selector:
    app: info-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
