# --- RabbitMQ Infrastructure ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672 # RabbitMQ Port
        - containerPort: 15672 # Management UI Port
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: amqp
  - port: 5672
    targetPort: 5672
  - name: mgmt
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
---
# --- Satcom Telemetry App ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satcom-statgen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satcom-statgen
  template:
    metadata:
      labels:
        app: satcom-statgen
    spec:
      containers:
      - name: satcom-statgen-app
        image: satcom-statgen:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"